#spring.data.mongodb.uri=mongodb://localhost:27017/product-servicespring.data.mongodb.url=mongodb://gavindu1995@gmail.com:desilva9598@localhost:27017/product-service?authSource=admin
#spring.data.mongodb.url=mongodb+srv://gavindu:199598@cluster0.kinjgih.mongodb.net/productdb
spring.data.mongodb.uri=mongodb://root:password@localhost:27017/productdb?authSource=admin
server.port=8081


